name: excercise-wandb
on: issue_comment

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  ghapi-exercise:
    if: (github.event.issue.pull_request != null) && contains(github.event.comment.body, '/wandb')
    runs-on: ubuntu-latest
    steps:        

    - name: Get repo contents
      uses: actions/checkout@v3

    - name: install dependencies
      run: pip install ghapi wandb

    - name: Parse value from the command
      id: get-runid-value
      shell: python
      run: |
        import re, os
        comment = os.getenv('PR_COMMENT', '')
        match = re.search('/wandb[\s+](\S+)', comment)

        with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
          if match:
            print(f'VAL_FOUND=true', file=f)
            print(f'RUN_ID={match.group(1)}', file=f)
          else:
            print(f'VAL_FOUND=false', file=f)
      env:
        PR_COMMENT: ${{ github.event.comment.body }}

      
